In [42]:
import mglearn
import sklearn
import matplotlib.pyplot as plt
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB

# Классификатор BernoulliNB

X = np.array([[0, 1, 0, 1], [1, 0, 1, 1], [0, 0, 0, 1], [1, 0, 1, 0]])
y = np.array([0, 1, 0, 1])

counts = {}
for label in np.unique(y):
 counts[label] = X[y == label].sum(axis=0)
print("Частоты признаков:\n{}".format(counts))

clf = BernoulliNB()
clf.fit(X, y)
print("1 clf.predict:\n{}".format(clf.predict(X[0:4])))
# Классификатор MultinomialNB

rng = np.random.RandomState(1)
X = rng.randint(25, size=(6, 10))
y = np.array([1, 2, 3, 4, 5, 6])

clf = MultinomialNB()
clf.fit(X, y)

print("2 clf.predict:\n{}".format(clf.predict(X[0:6])))
print(X[0:5])
# Классификатор GaussianNB

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])
clf = GaussianNB()
clf.fit(X, Y)

print("3 clf.predict:\n{}".format(clf.predict([[1, -1]])))


clf_pf = GaussianNB()
clf_pf.partial_fit(X, Y, np.unique(Y))

print("4 clf.predict:\n{}".format(clf_pf.predict([[-0.8, 3]])))



Частоты признаков:
{0: array([0, 1, 0, 2]), 1: array([2, 0, 2, 1])}
1 clf.predict:
[0 1 0 1]
2 clf.predict:
[1 2 3 4 5 6]
[[ 5 11 12  8  9 11  5 15  0 16]
 [ 1 12  7 13  6 18 20  5 18 20]
 [11 10 14 18  4 23 23  9 17 23]
 [ 0 22 13  9  9  7 22  1  0 17]
 [ 8 24 13 19 15 10  8  7  3  6]]
3 clf.predict:
[1]
4 clf.predict:
[2]
